#!/usr/bin/env Rscript

library(optparse)

option_list = list(
  make_option(c("-i", "--input"), type="character", default="population.csv", 
              help="input CSV population file"),
  make_option(c("-o", "--output"), type="character", default="mutation_rate_estimates.csv", 
              help="output CSV file of mutation estimates"),
  make_option(c("-m", "--minimum-mutated-plasmids"), type="integer", default=1, 
              help="number of mutant plasmids a cell must have to count as a mutant")
)
  
usage_string = paste(
  "Input should be the population file generated by plasmrs.py",
  sep = ""
) 

opt_parser = OptionParser(usage=usage_string, option_list=option_list);
opt = parse_args(opt_parser);

require(rsalvador)
require(dplyr)
require(ggplot2)

# mutant_plasmid_threshold is the *number* of plasmids that must be present for it to count as a
# mutant detected by the Luria-Delbrück fluctuation test
estimateMutRate <- function(population_filename, mutant_plasmid_threshold) {
  print(population_filename)
    data = read.csv(population_filename, header=T)  
    data$key = paste(data$N_0, data$N, data$N_p, data$u_p, sep="/");
    
    est = data.frame()
    for (on_key in unique(data$key)) {
      print(on_key)
      key_pieces = unlist(strsplit(on_key, "/"))
      key_N_0 = as.numeric(key_pieces[1])
      key_N = as.numeric(key_pieces[2])
      key_N_p = as.numeric(key_pieces[3])
      key_u_p = as.numeric(key_pieces[4])
      
      key_data = data %>% filter(key==on_key)
      
      print(nrow(key_data))
      
      #Loop over replicates

      m_counts = c()
      for (on_repl in unique(key_data$repl)) {
        repl_m = 0
        repl_data = key_data %>% filter(repl==on_repl)
        for (i in 1:nrow(repl_data)) {
          if (repl_data$p_mut[i] >= mutant_plasmid_threshold) {
            repl_m = repl_m + repl_data$cells[i]
          }
        }
        
        m_counts = c(m_counts, repl_m)
      }

      key_mu = tryCatch({
        newton.LD(m_counts)/key_N
      }, warning = function(w) {
        NA
      }, error = function(e) {
        NA
      }, finally = {
      })
      
      key_my_ci = tryCatch({
        confint.LD(m_counts, alpha=0.05, init.lower=0)/key_N
      }, warning = function(w) {
        c(NA,NA)
      }, error = function(e) {
        c(NA,NA)
      }, finally = {
      })
      

      key_row = data.frame(N_0 = key_N_0, 
                           N = key_N,
                           N_p = key_N_p, 
                           u_p = key_u_p, 
                           repl = length(unique(key_data$repl)),
                           mu = key_mu,
                           mu_95L = key_my_ci[1],
                           mu_95U = key_my_ci[2],
                           mut_p_min = mutant_plasmid_threshold
                           )
      est = est %>% bind_rows(key_row)
    }
    
    return(est)
}

est = estimateMutRate(population_filename = opt$input, mutant_plasmid_threshold = opt$'minimum-mutated-plasmids')
write.csv(est,opt$output, row.names=F)
